### ISSUE TITLE
The colormap is changed by using plot2svg

### ISSUE THREAD

**Issue by TheInvisible84** [kupiqu/plot2svg#7] opened 2018-09-27 14:57 UTC
Hej I just came along your plot2svg.
And it seems working as I need it, but for my imagesc() plot with colormap hot (I tried also other) it always changes it to the colormap parula. Can you fix that or identify where the problem lays then I might be able to fix it myself.

**Comment by kupiqu** [comment] 2018-09-27 15:00
Mmm, thanks for letting me know. I'll take a look asap...

**Comment by kupiqu** [comment] 2018-09-27 15:01
btw, a brief code snippet of the problem would be helpful for debugging

**Comment by TheInvisible84** [comment] 2018-09-27 16:04
`imagesc(peaks);
axis off equal; colormap hot;
colorbar;
plot2svg`

that shows the issue already

**Comment by TheInvisible84** [comment] 2018-09-27 16:08
It saves it nicely but with the parula colormap
I guess it is some indexing error as the parula is the first colormap what is shown in the matlab colormaps?
So instead of taking the actual colormap it takes just always the first.

**Comment by kupiqu** [comment] 2018-09-27 16:24
I can reproduce the issue

**Comment by kupiqu** [comment] 2018-09-27 16:45
I think I know what's going on, i.e. where the issue is. Now I need to know how to properly fix it :)

**Comment by kupiqu** [comment] 2018-09-27 16:54
fixed with commit d0e666cd41f774387a2d3f69a250d417c6801a16

**Closed as completed by kupiqu** 2018-09-27 16:54 UTC
Labels: bug, fixed

**Comment by TheInvisible84** [comment] 2018-09-27 19:49
great Thank you soooo much

**Comment by kupiqu** [comment] 2018-09-27 20:43
welcome
