### ISSUE TITLE
Bug fixes in fig2svg.m

### ISSUE THREAD

**Issue by altmany** [kupiqu/plot2svg#21] opened 2019-06-30 13:37 UTC
1. In fig2svg.m line #620, `...lenght(...` should be `**length(**`
2. In fig2svg.m line #713, the `default` variable is not defined
3. In fig2svg.m line #987, the `axzindex_inner` variable is not defined

**Comment by kupiqu** [comment] 2019-07-01 18:53
from master:

- line #620 `end`
- line #713 `end`
- line #987 `minor_axytick = [];`

are you up-to-date with the master version? 

or, what release are you using?

In the meantime, I'll check out the last release for the case I forgot to update...

**Comment by kupiqu** [comment] 2019-07-01 18:57
It seems everything is right in version 2019.05.2. Closing...

If you use this version and have problems, please tell.

**Comment by altmany** [comment] 2019-07-01 19:11
The bugs still exist in the latest version:

1. In fig2svg.m line #**646**, `...lenght(...` should be **`length(`**
2. In fig2svg.m line #**755**, the `default` variable is not defined
3. In fig2svg.m line #**1012**, the `axzindex_inner` variable is not defined

**Comment by kupiqu** [comment] 2019-07-01 19:22
1. Fixed (Thanks!)
2. It seems `default` is only used if nargin >= 5 according to the if conditional. Can you give me a minimal code example of the error?
3. There is an exemption for colorbars, perhaps I need to add more, or who knows. Again, can you give me an minimal code example of the error?

**Comment by kupiqu** [comment] 2019-07-01 19:29
Regarding 3, I guess I can do:

```
      if ~strcmp(get(ax, 'Type'), 'colorbar')
        if strcmp(get(ax, 'Box'), 'on')
          axzindex_inner = find((axztick > axlimori(3)) & (axztick < (axlimori(3)+axlimori(6))));
        else
          axzindex_inner = find((axztick >= axlimori(3)) & (axztick <= (axlimori(3)+axlimori(6))));
        end
        valid_zsticks = axzindex_inner;
      end
```

but I am not totally sure how this piece of code is used, perhaps I shouldn't use the following at all:

```
      if ~strcmp(get(ax, 'Type'), 'colorbar')
        valid_zsticks = axzindex_inner;
      end
```

Having access to the code that triggered the error would be nice to have some context...

**Comment by altmany** [comment] 2019-07-01 19:32
There's no context I'm afraid - these bugs were discovered using static analysis by Matlab's Dependency tool - add fig2svg as a Matlab "Project" and you'll see what I mean.

**Comment by kupiqu** [comment] 2019-07-01 19:39
Mmm, ok. It's fine, I believe you.

I fixed 1 and 3, as indicated above, but I don't think I can do much about 2. 

In fact, why is it any different in line #755 than in line #776 (and other instances)? I guess that tool doesn't like having variables appearing that way, but it only triggers the issue the first time?

**Comment by kupiqu** [comment] 2019-07-01 19:43
Oh, I see, the issue is in fact in line 738. Fixed!

**Closed as completed** 2019-07-01 19:45 UTC
Labels: bug, fixed
