### ISSUE TITLE
Added scalebar leads to error

### ISSUE THREAD

**Issue by TheInvisible84** [kupiqu/plot2svg#8] opened 2018-09-28 08:08 UTC
```
imagesc(peaks); axis off equal; colormap hot; colorbar; hold on

sizex=90000; sizey=90000; nx=49; ny=49; pixelx=sizex/nx; pixely=sizey/ny;

if sizex> 30000
  scalebar=10000;
  SBname='10 µm';
elseif sizex> 15000
  scalebar=5000;
  SBname='5 µm';
elseif sizex> 3000
  scalebar=1000;
  SBname='1 µm';
elseif sizex<3000
  scalebar=500;
  SBname='500 nm';
end

SBx = [ nx-(nx*0.1)-(scalebar/pixelx) nx-(nx*0.1)-(scalebar/pixelx) nx-(nx*0.1);
            nx-(nx*0.1) nx-(nx*0.1)-(scalebar/pixelx) nx-(nx*0.1)];
SBy = [ ny-(ny*0.1) ny-(ny*0.1)-(scalebar/pixelx*0.1) ny-(ny*0.1)+(scalebar/pixelx*0.1)
            ny-(ny*0.1) ny-(ny*0.1)+(scalebar/pixelx*0.1) ny-(ny*0.1)-(scalebar/pixelx*0.1)];
plot(SBx,SBy,'LineWidth',3,'Color','w')
text((SBx(1,1)+SBx(2,1))/2,SBy(1,1)+(scalebar/pixelx*0.4),SBname,'Color','w','FontSize',24,'HorizontalAlignment','center')
plot2svg
```

When I add a scalebar in the image I get the following error:

> Error using matlab.graphics.primitive.Image/get
There is no ZData property on the Image class.
>
>Error in plot2svg>AxesChildBounds (line 4464)
          data = reshape(get(dataObjs(j), axisData{i}), [], 1);
>
>Error in plot2svg>get_projection (line 4211)
      [xinfi, yinfi, zinfi] = AxesChildBounds(ax);
>
>Error in plot2svg>axes2svg (line 1230)
  [projection,edges] = get_projection(ax,id);
>
>Error in plot2svg (line 202)
      group = axes2svg(fid,id,ax(j),group,paperpos);

or should I add the scalebar in a different way?

**Comment by kupiqu** [comment] 2018-09-28 13:39
Can you format the following 2 instructions properly so I can try to reproduce the issue?

SBx = [ nx-(nx0.1)-(scalebar/pixelx) nx-(nx0.1)-(scalebar/pixelx) nx-(nx0.1);
nx-(nx0.1) nx-(nx0.1)-(scalebar/pixelx) nx-(nx0.1)];
SBy = [ ny-(ny0.1) ny-(ny0.1)-(scalebar/pixelx0.1) ny-(ny0.1)+(scalebar/pixelx0.1)
ny-(ny0.1) ny-(ny0.1)+(scalebar/pixelx0.1) ny-(ny0.1)-(scalebar/pixelx0.1)];

**Comment by TheInvisible84** [comment] 2018-09-28 16:46
before every 0.1 need to be a '*' (multiply with symbol) gets somehow deleted when writing here

**Comment by kupiqu** [comment] 2018-09-28 16:52
use ``` before and after to indicate multiline code, that should fix the markdown format issue

**Comment by kupiqu** [comment] 2018-09-28 16:53
I did this for you in the original submission, didn't know I could do this myself

**Comment by TheInvisible84** [comment] 2018-09-28 16:56
`SBx = [ nx-(nx*0.1)-(scalebar/pixelx) nx-(nx*0.1)-(scalebar/pixelx) nx-(nx*0.1);
nx-(nx*0.1) nx-(nx*0.1)-(scalebar/pixelx) nx-(nx*0.1)];
SBy = [ ny-(ny*0.1) ny-(ny*0.1)-(scalebar/pixelx*0.1) ny-(ny*0.1)+(scalebar/pixelx*0.1)
ny-(ny*0.1) ny-(ny*0.1)+(scalebar/pixelx*0.1) ny-(ny*0.1)-(scalebar/pixelx*0.1)];`

**Comment by kupiqu** [comment] 2018-09-28 16:57
yeah, yeah, I got it, I actually edited the original submission.

will take a look as soon as possible

**Comment by kupiqu** [comment] 2018-09-28 18:08
Sorry, but I cannot reproduce any error in my system. What matlab version are you using?

**Comment by kupiqu** [comment] 2018-09-28 18:12
I get an error in Octave though...

**Comment by kupiqu** [comment] 2018-09-28 18:52
it should be fixed with commit 613b0f174681dad23cc4c66ea4f9975066ed25b6

please reopen otherwise

**Closed as completed by kupiqu** 2018-09-28 18:52 UTC
Labels: bug, fixed

**Comment by TheInvisible84** [comment] 2018-10-01 10:15
Hej Thanks it works now just that the 10 µm is not as 10 µm exported in the svg its a "10       m"
it seems to be an issue with the µ as when I have a "nm" as scalebar it works well.

**Comment by kupiqu** [comment] 2018-10-01 10:56
Mmm, that's weird. I fixed that as well in both Matlab 2018b and Octave. What Matlab version do you have?

**Comment by TheInvisible84** [comment] 2018-10-01 11:24
I have Matlab2018a so you say when I update it should work?

**Comment by kupiqu** [comment] 2018-10-01 12:04
Maybe, but I don't think so. 

What OS do you use? 

But more important perhaps, what text file encoding?

**Comment by kupiqu** [comment] 2018-10-01 12:11
Ok, (I think) I figured this out.

Matlab console does not interpret µ as an input, but this just works fine if the code is run from a file (at least in my system). Please try it out

**Comment by TheInvisible84** [comment] 2018-10-01 12:42
I run it from a script file

Have Win10 at least here at my work PC can try at home what my win7 says

**Comment by kupiqu** [comment] 2018-10-01 13:00
can you attach the file? it will have another encoding (different from UTF-8, which I use) and maybe I find a solution

it would be good if you open a different bug specifically for this, to which we will refer and further discuss (all current discussion is not related to the original issue, which is resolved).
